# Generated by Django 3.0.3 on 2020-03-04 18:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vistoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.TextField(default='none')),
                ('fotoCompilada', models.ImageField(blank=True, null=True, upload_to='')),
                ('coordenadoria', models.CharField(max_length=80)),
                ('numeroDoRelatorio', models.CharField(max_length=15)),
                ('unidadeFederativa', models.CharField(default='SC', max_length=2)),
                ('municipio', models.CharField(max_length=50)),
                ('cobrade', models.CharField(max_length=12)),
                ('descricaoCobrade', models.CharField(max_length=50)),
                ('dataHoraRegistrado', models.DateTimeField(default=django.utils.timezone.now)),
                ('dataHoraDesastre', models.CharField(max_length=40)),
                ('descricaoDesastre', models.TextField()),
                ('quantiadeObitos', models.IntegerField(default=0)),
                ('quantiadePopuIsolada', models.IntegerField(default=0)),
                ('quantidadeDesalojados', models.IntegerField(default=0)),
                ('populacaoAfetada', models.IntegerField(default=0)),
                ('pocentagemPopulacaoAfetada', models.FloatField(default=0)),
                ('habitacoesAtingidas', models.IntegerField(default=0)),
                ('interrupcaoDeServi', models.TextField(default='Não afetada')),
                ('infraPublica', models.TextField(default='Não afetada')),
                ('economiaPrivada', models.TextField(default='Não afetada')),
                ('ambiente', models.TextField(default='Não afetada')),
                ('iah', models.TextField(default='Não fornecidas')),
                ('desobistrucaoVias', models.FloatField(default=100)),
                ('reestabelecimentoServicos', models.TextField(default='Não afetada')),
                ('classificacao', models.IntegerField(default=0)),
                ('homologacao', models.BooleanField(default=False)),
                ('infosGerais', models.TextField()),
                ('latitude', models.CharField(max_length=20)),
                ('longitude', models.CharField(max_length=20)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='autor_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
