# Generated by Django 2.1 on 2020-02-18 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relatorios', '0002_auto_20200218_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vistoria',
            name='fotoCompilada',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
